name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm install
      - name: Check lint
        run: npm run lint
      